version: '3.1'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:${APP_PORT}"
    environment:
      NODE_ENV: development
      APP_PORT: ${APP_PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      DATABASE_URL: mongodb://${DB_USER}:${DB_PASS}@db:27017/${DB_NAME}
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./db-data:/data/db

volumes:
  db-data: {}
