
export const FETCHING_POST = 'FETCHING_POST';
export const FETCHING_POST_SUCCESS = 'FETCHING_POST_SUCCESS';
export const FETCHING_POST_FAIL = 'FETCHING_POST_FAIL';

export const FETCHING_POSTS = 'FETCHING_POSTS';
export const FETCHING_POSTS_SUCCESS = 'FETCHING_POSTS_SUCCESS';
export const FETCHING_POSTS_FAIL = 'FETCHING_POSTS_FAIL';
